### ISSUE TITLE
bug in paper

### ISSUE THREAD

**Issue by ctb** [phiweger/nanotext#1]
line 108 of https://www.biorxiv.org/content/early/2019/01/18/524280, coprus -> corpus

**Comment by phiweger** [comment]
good catch thank you! corrected manuscript and uploaded new version to bioRxiv.

**Comment by ctb** [comment]
another typo - 'vocavulary'

**Comment by ctb** [comment]
also line 146 do you mean 'genomes' instead of 'metagenomes'?

**Comment by phiweger** [comment]
argh ... thanks, corrected.
