### ISSUE TITLE
suggest using organization rather than personal account

### ISSUE THREAD

**Issue by ctb** [phiweger/nanotext#2]
e.g. github.com/nanotext/nanotext/. I've grabbed github.com/nanotext/ as an org, happy to transfer it over to you @phiweger!

**Comment by phiweger** [comment]
thank you that would be very kind! what would you say is the main advantage of using an organisation instead of the "classical" repo?

**Comment by ctb** [comment]
It’s not tied to your account inextricably so if you move on from the project, you can turn maintenance over to others.

If you want to have sister repos that contain examples, it’s nice to group them (see spacegraphcats).

And there aren’t any downsides AFAIK :)

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Jan 20, 2019, at 2:41 PM, Adrian Viehweger <notifications@github.com<mailto:notifications@github.com>> wrote:


thank you that would be very kind! what would you say is the main advantage of using an organisation instead of the "classical" repo?

**Comment by phiweger** [comment]
ah I see, convinced :)

**Comment by ctb** [comment]
invited you! once you're on, please feel free to go ahead and remove me :)

**Comment by phiweger** [comment]
thanks a lot, I'll complete some more code and then transfer the repo :)
