### ISSUE TITLE
how do you make the domtbl.tsv file from a genome?

### ISSUE THREAD

**Issue by ctb** [phiweger/nanotext#4]
the corpus training finished! ~3 hours and 10 GB RAM on a recent MacBook Pro. eagerly awaiting instructions for next steps :)

**Comment by phiweger** [comment]
Hi, 

I put the (rough) Snakemake workflow here:

[`nanotext/workflows/annotation_tara`](https://github.com/phiweger/nanotext/tree/master/nanotext/workflows/annotation_tara)

There are 3 steps:

1. call ORFs w/ `prodigal`
2. `hmmscan` against the Pfam database (v32)
3. reformat domtbl output and filter using an external script `HmmPy.py` I put in [`nanotext/scripts/external`](https://github.com/phiweger/nanotext/tree/master/nanotext/scripts/external)

It's not a pretty workflow yet sorry, but all settings are documented -- if you have problems getting it to work I'll make time to clean it up quickly :)

**Comment by phiweger** [comment]
Ok @ctb , so I couldn't leave you with this state of affairs, the workflow condition was too shameful ;)

I cleaned it up and provided an example and documentation [here](https://github.com/phiweger/nanotext/tree/master/nanotext/workflows/annotation_tara).

Does that work for you?

**Comment by ctb** [comment]
wow, thank you! I will give it a try :)

**Comment by ctb** [comment]
It worked! I needed to download and hmmpress `Pfam-a.hmm`, and then after running the workflow I got a bunch of results:

```
ls -R results
data    log

results/data:
TARA_ION_MAG_00012

results/data/TARA_ION_MAG_00012:
orfs.domtbl     orfs.domtbl.tsv orfs.fa

results/log:
hmm             prodigal

results/log/hmm:
TARA_ION_MAG_00012.log

results/log/prodigal:
TARA_ION_MAG_00012.log
```

I will try working with `results/data/TARA_ION_MAG_00012/orfs.domtbl.tsv`!

**Comment by ctb** [comment]
...and IT'S ALIIIIIIIIIIIVE!!!

```
% mv orfs.domtbl.tsv TARA_ION_MAG_00012.domtbl.tsv
% nanotext search \
>     --embedding data/embedding.genomes.model \
>     --genome data/TARA_ION_MAG_00012.domtbl.tsv \
>     --topn 3 --out -
```

yields

```
Loading model ...
Inferring genome vector ...
GCF_000759935.1 0.9384
GCF_000759855.1 0.9383
GCF_001180325.1 0.9374
Done.
```

**Comment by phiweger** [comment]
Perfect! All _Prochlorococcus_. Thanks Titus for giving it a try.
